### ISSUE TITLE
Simulink documentation

### ISSUE THREAD

**Issue by asr** [eafit-apolo/apolo-docs#3]
@mgomezzul, I couldn't find the Simulink documentation. Where is it?

**Comment by mgomezzul** [comment]
@asr The Simulink documentation (example) is present on the Usage page (Software> Programming Languages > MATLAB > MATLAB R2018a > Usage > MDCS using a local MATLAB client > Submitting jobs > Serial Jobs > Numeral six (6.)

**Comment by asr** [comment]
Thanks!
